version: 2.1

orbs:
  node: circleci/node@5.0.3
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  build:
    docker:
      - image: "cimg/node:14.15"
    steps:
      - node/install:
          node-version: '14.15'
      - checkout
      - run:
          name: Verify Node and NPM Versions
          command: |
            echo "NODE --version"
            node --version
            echo "NPM --version"
            npm --version
      - run:
          name: Install Front-End Dependencies
          command: npm run frontend:install
      - run:
          name: Install API Dependencies
          command: npm run api:install
      - run:
          name: Front-End Lint
          command: npm run frontend:lint
      - run:
          name: Front-End Build
          command: npm run frontend:build
      - run:
          name: API Build
          command: npm run api:build

  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: '14.15'
      - checkout
      - eb/setup
      - aws-cli/setup
      - run:
          name: Deploy Application
          command: |
            npm run frontend:install
            npm run frontend:build
            npm run frontend:deploy
            npm run api:install  # Fixed typo: was 'ap:install'
            npm run api:build
            npm run api:deploy

workflows:
  udagram:
    jobs:
      - build
      - hold:
          filters:
            branches:
              only:
                - master
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
